# Generated by Django 4.0.3 on 2023-07-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_branch_course_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='student_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
