# Generated by Django 4.0.3 on 2023-07-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_studentreg_about_studibreeze_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreg',
            old_name='student_district',
            new_name='school_district',
        ),
    ]
