# Generated by Django 4.0.3 on 2023-07-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_student_district_studentreg_school_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='student_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
