# Generated by Django 4.0.3 on 2023-07-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_studentreg_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billingdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=500)),
                ('bill_no', models.CharField(blank=True, max_length=300)),
                ('date', models.CharField(blank=True, max_length=300)),
                ('amount', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
