# Generated by Django 4.0.3 on 2023-07-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_studentreg_studend_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdata',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='billingdata',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='join_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='student_id',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
