# Generated by Django 4.0.3 on 2023-07-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_billingdata_amount_alter_billingdata_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
